
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Doctor/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Doctor<small>List All</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Doctor</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('doctor_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="add new Doctor (Ctrl+a)" href="<?=  site_url('administrator/doctor/add'); ?>"><i class="fa fa-plus-square-o" ></i> Add New Doctor</a>
                        <?php }) ?>
                        <?php is_allowed('doctor_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export Doctor" href="<?= site_url('administrator/doctor/export'); ?>"><i class="fa fa-file-excel-o" ></i> Export XLS</a>
                        <?php }) ?>
                        <?php is_allowed('doctor_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export pdf Doctor" href="<?= site_url('administrator/doctor/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> Export PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Doctor</h3>
                     <h5 class="widget-user-desc">List All Doctor <i class="label bg-yellow"><?= $doctor_counts; ?>  items</i></h5>
                  </div>

                  <form name="form_doctor" id="form_doctor" action="<?= base_url('administrator/doctor/index'); ?>">
                  

                  <div class="row">
				  <div class="col-md-10">

                     <div class="form-group">
                        <p class="col-sm-3">Dr Code:
							<input type="text" class="form-control" name="DR_CODE" id="DR_CODE">
                        </p>
						
						<p class="col-sm-3">Dr Eng Name:
							<input type="text" class="form-control" name="E_NAME" id="E_NAME">
                        </p>
						
						<p class="col-sm-3">Dr Chi Name:
							<input type="text" class="form-control" name="C_NAME" id="C_NAME">
                        </p>
						
						<p class="col-sm-3">Center Tel:
							<input type="text" class="form-control" name="C_NAME" id="C_NAME">
                        </p>
						
						<p class="col-sm-3">Center Fax:
							<input type="text" class="form-control" name="C_NAME" id="C_NAME">
                        </p>
						
						<p class="col-sm-3">Term Date:
							<input type="text" class="form-control" name="C_NAME" id="C_NAME">
                        </p>
						
						<p class="col-sm-3">Status:
							<input type="text" class="form-control" name="STATUS" id="STATUS">
							
                        </p>
						
						<p class="col-sm-3">
						<div class="col-sm-1">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="filter search">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/doctor');?>" title="reset filters">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
					 </p>
						
					 </div>
					 
					
					 
					 
                  </div>
				  
				   
				  </div>
				  
				  <br>
				  
				  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>Dr Code</th>
                           <th>Dr Name</th>
                           <th>Center Tel</th>
						   <th>Center Fax</th>
						   <th>Term Date</th>
                           <th>Status</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_doctor">
                     <?php foreach($doctors as $doctor): ?>
                        <tr>
                           <td><?= _ent($doctor->DR_CODE); ?></td> 
                           <td>
								<?= _ent($doctor->E_TITLE); ?> &nbsp; <?= _ent($doctor->E_NAME); ?><br>
								<?= _ent($doctor->C_NAME) == "" ? "" : _ent($doctor->C_NAME)._ent($doctor->C_TITLE); ?>
							</td> 
							
							<?php
								$this->db->where("DR_CODE", _ent($doctor->DR_CODE));
								$this->db->where("DEFAULT_CENTER", "1");
								$query = $this->db->get("doctor_consult_hour");
								
								if ($query->num_rows() > 0){
									$center = $query->row();
								}else{
									$center = "";
								}
							?>
							
                           <td><?= $center == "" ? "" : $center->TEL; ?></td> 
						   <td><?= $center == "" ? "" : $center->FAX; ?></td> 
                           <td><?= _ent($doctor->TERM_DATE); ?></td> 
                           <td><?= _ent($doctor->STATUS); ?></td>  
                           <td width="200">
                              <?php is_allowed('doctor_view', function($doctor) use ($doctor){?>
                              <a href="<?= site_url('administrator/doctor/view/' . $doctor->DR_CODE); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> Details
                              <?php }) ?>
                              <?php is_allowed('doctor_update', function($doctor) use ($doctor){?>
                              <a href="<?= site_url('administrator/doctor/edit/' . $doctor->DR_CODE); ?>" class="label-default"><i class="fa fa-edit "></i> Update</a>
                              <?php }) ?>
                              <?php is_allowed('doctor_delete', function($doctor) use ($doctor){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/doctor/delete/' . $doctor->DR_CODE); ?>" class="label-default remove-data"><i class="fa fa-close"></i> Remove</a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($doctor_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Doctor data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Are you sure?",
          text: "data to be deleted can not be restored!",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes, delete it!",
          cancelButtonText: "No, cancel plx!",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_doctor').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "Are you sure?",
            text: "data to be deleted can not be restored!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/doctor/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "Please choose bulk action first!",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>