
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Doctor      <small>Detail Doctor</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/doctor'); ?>">Doctor</a></li>
      <li class="active">Detail</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Doctor</h3>
                     <h5 class="widget-user-desc">Detail Doctor</h5>
					 <ul class="nav nav-tabs">
					  <li id="doctortab" class="active"><a id="btn_doctor">Doctor</a></li>
					  <li id="qualitab" class=""><a id="btn_quali">Qualification</a></li>
					 </ul>
                  </div>

				 
                  <div class="form-horizontal" name="form_doctor" id="form_doctor" >
				  <div id="doctorDiv">
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DR CODE</label>

							<div class="col-sm-8">
								<?= _ent($doctor->DR_CODE); ?>
							</div>
                        </div>
                    
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CENTER CODE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->CENTER_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">E TITLE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->E_TITLE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">C TITLE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->C_TITLE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">E NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->E_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">C NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->C_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">GENDER </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->GENDER); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">BY APPOINTMENT </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->BY_APPOINTMENT); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PRINT </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->PRINT); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">VOUCHER ENTRY </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->VOUCHER_ENTRY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TYPE1 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->TYPE1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TYPE2 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->TYPE2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TYPE3 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->TYPE3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MOBILE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->MOBILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">EMAIL </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->EMAIL); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LANG </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->LANG); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DOB </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->DOB); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">HKID </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->HKID); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MPS EXPIRY DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->MPS_EXPIRY_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">APS EXPIRY DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->APS_EXPIRY_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">BR EXPIRY DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->BR_EXPIRY_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">GP REG NO </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->GP_REG_NO); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SP REG NO </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->SP_REG_NO); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">BUPA LOGIN </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->BUPA_LOGIN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">BUPA PASSWORD </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->BUPA_PASSWORD); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">BILL TO DR CODE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->BILL_TO_DR_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PAYEE NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->PAYEE_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PAYEE ADDR1 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->PAYEE_ADDR1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PAYEE ADDR2 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->PAYEE_ADDR2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PAYEE ADDR3 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->PAYEE_ADDR3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PAYEE ADDR4 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->PAYEE_ADDR4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PAYEE ADDR5 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->PAYEE_ADDR5); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PAYEE DISTRICT </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->PAYEE_DISTRICT); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PREVIOUS PAYEE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->PREVIOUS_PAYEE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">E SPECIALTY1 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->E_SPECIALTY1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">E SPECIALTY2 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->E_SPECIALTY2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">E SPECIALTY3 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->E_SPECIALTY3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">E SPECIALTY4 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->E_SPECIALTY4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">C SPECIALTY1 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->C_SPECIALTY1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">C SPECIALTY2 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->C_SPECIALTY2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">C SPECIALTY3 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->C_SPECIALTY3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">C SPECIALTY4 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->C_SPECIALTY4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ADMISSION RIGHT </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->ADMISSION_RIGHT); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MEDICAL PROCEDURE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->MEDICAL_PROCEDURE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">START DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->START_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TERM DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->TERM_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ATTN </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->ATTN); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">REMARK </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->REMARK); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">EXPIRY </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->EXPIRY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UDF1 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->UDF1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UDF2 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->UDF2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UDF3 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->UDF3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UDF4 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->UDF4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UDF5 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->UDF5); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAST MODIFIER </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->LAST_MODIFIER); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAST UPDATE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor->LAST_UPDATE); ?>
                        </div>
                    </div>
					</div>
					
					<div id="qualiDiv">
					<?php 
							echo "<script>console.log('test 03');</script>";
							$idx = 0; 
							$quali = array();
							if ($doctor_qualifications != null){
							foreach($doctor_qualifications as $doctor_qualification):
							$idx++; 
							if ($idx != 1){ echo "<hr>"; }
						?>
						<h3>Qualification <?= $idx; ?></h3>
		
					<div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">QUALIFICATION CODE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->QUALIFICATION_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DR CODE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->DR_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">QUALIFICATION </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->QUALIFICATION); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CERT YEAR </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->CERT_YEAR); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UDF1 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->UDF1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UDF2 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->UDF2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UDF3 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->UDF3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UDF4 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->UDF4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">UDF5 </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->UDF5); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAST MODIFIER </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->LAST_MODIFIER); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAST UPDATE </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_qualification->LAST_UPDATE); ?>
                        </div>
                    </div>
							<?php endforeach; }else{ echo "<h3><center>***** This doctor have not insert any qualification *****</center></h3><br><br>"; } ?>
					</div>
					</div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('doctor_update', function($doctor) use ($doctor){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit doctor (Ctrl+e)" href="<?= site_url('administrator/doctor/edit/'.$doctor->DR_CODE); ?>"><i class="fa fa-edit" ></i> Edit Doctor</a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/doctor/'); ?>"><i class="fa fa-undo" ></i> Go Doctor List</a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){
	$('#qualiDiv').hide();
	  
	  
	  $('#btn_doctor').click(function(){
		  $('#doctorDiv').show();
		  $('#doctortab').addClass('active');
		  $('#qualiDiv').hide();
		  $('#qualitab').removeClass('active');
	  });
	  
	  $('#btn_quali').click(function(){
		  $('#qualiDiv').show();
		  $('#qualitab').addClass('active');
		  $('#doctorDiv').hide();
		  $('#doctortab').removeClass('active');
	  });
});
</script>
